# Yellow Examples

In [2]:
yellow_follow = 'C:/Users/caspe/Desktop/yellow/lib/'

import sys; sys.path.append(yellow_follow) 
from sen2mosaic.get_bounds import get_bounds
from sen2mosaic.download import connectToAPI, search, download
from raster_io import raster_to_array, array_to_raster, raster_to_metadata

In [4]:
# Lets download a sentinel1 and 2 image
project_geom = 'C:/Users/caspe/Desktop/yellow/geometry/copenhagen.shp'
download_folder = 'C:/Users/caspe/Desktop/yellow_example/'

bounds = get_bounds(project_geom)
bounds

[{'name': '33UUB',
  'bounds': [11.800511439000047,
   54.91902653800008,
   13.591601298000057,
   55.93727334500005]}]

In [5]:
# Download a tile
api_connection = connectToAPI('casperfibaek', 'Goldfish12')

sdf = search(bounds[0]["name"], level='2A', start='20210101', end='20210201', maxcloud=20, minsize=100.0)
download(sdf, download_folder)

Skipping file S2A_MSIL2A_20210116T102351_N0214_R065_T33UUB_20210116T115302.SAFE, as it has already been downloaded in the directory C:/Users/caspe/Desktop/yellow_example/. If you want to re-download it, delete it and run again.


[]

In [6]:
# Lets read the downloaded rasters
b04_ref = download_folder + 'b04.jp2'
b08_ref = download_folder + 'b08.jp2'
b04 = raster_to_array(b04_ref)
b08 = raster_to_array(b08_ref)

In [7]:
b04

array([[3753, 3764, 3689, ..., 8304, 3882, 5760],
       [3469, 3580, 3472, ..., 4352, 5500, 5512],
       [3194, 3241, 3083, ..., 5928, 6608, 5329],
       ...,
       [ 735,  767,  752, ...,   81,   92,   17],
       [ 777,  781,  774, ...,   88,  110,   81],
       [ 772,  791,  785, ...,   86,   66,   53]], dtype=uint16)

In [8]:
# Lets calculate some index
from stats_indices import calc_indices
ndvi = calc_indices('ndvi', B04=b04, B08=b08)
ndvi

array([[ 0.03620955,  0.03089598,  0.0384465 , ...,  0.01751065,
         0.02657974, -0.03448276],
       [ 0.03154662,  0.01540154,  0.03111483, ...,  0.03030303,
        -0.00732601, -0.00510576],
       [ 0.02054584,  0.01083473,  0.03641194, ..., -0.04109589,
        -0.00823924, -0.01485431],
       ...,
       [ 0.59064327,  0.57659398,  0.57199772, ..., -0.76086957,
        -0.97849462, -0.88888889],
       [ 0.57342849,  0.57542811,  0.55517241, ..., -0.51724138,
        -0.375     , -0.52830189],
       [ 0.57442117,  0.56430735,  0.55511476, ..., -0.33333333,
        -0.45054945, -0.96296296]])

In [9]:
# Saving the raster back
array_to_raster(ndvi, out_raster=download_folder + 'ndvi.tif', reference_raster=b04_ref)

'C:\\Users\\caspe\\Desktop\\yellow_example\\ndvi.tif'

In [11]:
# What about some textures?
from stats_filters import mad_std_filter
b4_mad = mad_std_filter(b04, width=5)
array_to_raster(b4_mad, out_raster=download_folder + 'b04_mad.tif', reference_raster=b04_ref)

'C:\\Users\\caspe\\Desktop\\yellow_example\\b04_mad.tif'

In [8]:
# What about some textures?
from stats_filters import standard_deviation_filter
b8_std = standard_deviation_filter(b08, width=3)
array_to_raster(b8_std, out_raster=download_folder + 'b08_std3.tif', reference_raster=b08_ref)

'C:\\Users\\caspe\\Desktop\\yellow_example\\b08_std3.tif'

In [17]:
array_to_raster((b04 > 200).astype('uint8'), out_raster=download

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=uint8)

In [18]:
deep_learning_input = np.concatenate([b4, b8, b4_mad, ndvi], axis=1)

array([[ 0.03620955,  0.03089598,  0.0384465 , ...,  0.01751065,
         0.02657974, -0.03448276],
       [ 0.03154662,  0.01540154,  0.03111483, ...,  0.03030303,
        -0.00732601, -0.00510576],
       [ 0.02054584,  0.01083473,  0.03641194, ..., -0.04109589,
        -0.00823924, -0.01485431],
       ...,
       [ 0.59064327,  0.57659398,  0.57199772, ..., -0.76086957,
        -0.97849462, -0.88888889],
       [ 0.57342849,  0.57542811,  0.55517241, ..., -0.51724138,
        -0.375     , -0.52830189],
       [ 0.57442117,  0.56430735,  0.55511476, ..., -0.33333333,
        -0.45054945, -0.96296296]])